---
# directory
- name: Ensure folders exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  loop:
  - "/opt/{{ pb_container_name }}-{{ pb_instance_name }}"
  - "/opt/{{ pb_container_name }}-{{ pb_instance_name }}/data"
  - "/opt/{{ pb_container_name }}-{{ pb_instance_name }}/public"

# copy configuration
- name: Ensure pocketbase network is present
  template:
    src: podman-pocketbase.network.j2
    dest: "{{ pb_quadlet_path }}/{{ pb_container_name }}-{{ pb_instance_name }}-net.network"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
    force: true

- name: Ensure pocketbase container is present
  template:
    src: podman-pocketbase.container.j2
    dest: "{{ pb_quadlet_path }}/{{ pb_container_name }}-{{ pb_instance_name }}.container"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
    force: true

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
    scope: "{{ pb_systemd_scope }}"

- name: Ensure systemd service is running
  ansible.builtin.systemd:
    name: "{{ pb_container_name }}-{{ pb_instance_name }}.service"
    state: started
    enabled: true
    scope: "{{ pb_systemd_scope }}"
